@API_HostAddress = https://localhost:7257

# GET {{API_HostAddress}}/api/ticket/getTicket/5D244CC3-6226-4323-A9EF-50012E4A014C
# POST {{API_HostAddress}}/api/ticket/createTicket
# Content-Type: application/json
# Accept: application/json
# {
#   "reason": "Test Reason",
#   "customerid": "8a49e30e-d753-44cc-b3eb-9634cb4bf98c"
# }
POST {{API_HostAddress}}/api/user/createUser
Content-Type: application/json
Accept: application/json
{
  "firstName": "Test", 
  "lastName": "Test", 
  "email": "test@test.de", 
  "password": "test"
}

###
  