services:
  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - './data/mailpit:/data'
    ports:
      - '8025:8025'
      - '1025:1025'
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:8025']
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    container_name: crdb
    hostname: crdb
    image: cockroachdb/cockroach:latest
    command: start-single-node --cluster-name=crdb-single-node --insecure
    restart: unless-stopped
    volumes:
      - './data/crdb:/cockroach/cockroach-data'
    ports:
      - '26257:26257'
    healthcheck:
      test: [CMD, curl, -f, 'http://localhost:8080']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  default:
    name: shared_network
